apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: default
  labels:
    app: consumer
spec:
  replicas: 1
  template:
    metadata:
      name: consumer
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: consumer:1.0
          imagePullPolicy: Never

          #              端口
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: consumer
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: default
spec:
  selector:
    app: consumer
  ports:
    # 33061
    - port: 8080
      name: rpc
      nodePort: 31080
      targetPort: 8080
      protocol: TCP
  type: NodePort
---
#provider
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider
  namespace: default
  labels:
    app: provider
spec:
  replicas: 1
  template:
    metadata:
      name: provider
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: provider:1.0
          imagePullPolicy: Never

          #              端口
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: provider
---
apiVersion: v1
kind: Service
metadata:
  name: provider
  namespace: default
spec:
  selector:
    app: provider
  ports:
    # 33061
    - port: 8080
      name: rpc
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
